b2cshop/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/login', to: 'sessions#new', as: :login_form
  post '/login', to: 'sessions#create', as: :login
  delete '/logout', to: 'sessions#destroy', as: :logout

  resources :users

  namespace :admin do
    root 'session#new'
    resources :categories
  end

end

b2cshop/app/views/layouts/_admin_menu.html.erb
<div class="bg-gray-800">
  <div class="max-w-7xl mx-auto px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <img class="h-8 w-8" src="https://tailwindui.com/img/logos/workflow-mark-indigo-500.svg" alt="Workflow">
        </div>
        <div class="ml-10 flex items-baseline space-x-4">
          <a href="<%= admin_root_path %>" class="nav-<%= request.fullpath == admin_root_path ? 'active' : 'normal' %>">Home</a>
          <a href="<%= admin_categories_path %>" class="nav-<%= request.fullpath == admin_categories_path ? 'active' : 'normal' %>">Category</a>
        </div>
      </div>
      <div>
        <%= link_to "Logout", logout_path, method: :delete, class: "text-white cursor-pointer" %>
      </div>
    </div>
  </div>
</div>

b2cshop/app/views/layouts/_menu.html.erb
<div class="bg-gray-800">
  <div class="max-w-7xl mx-auto px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <img class="h-8 w-8" src="https://tailwindui.com/img/logos/workflow-mark-indigo-500.svg" alt="Workflow">
        </div>
        <div class="ml-10 flex items-baseline space-x-4">
          <a href="<%= admin_root_path %>" class="nav-<%= request.fullpath == admin_root_path ? 'active' : 'normal' %>">Admin</a>
          <a href="<%= admin_categories_path %>" class="nav-<%= request.fullpath == admin_categories_path ? 'active' : 'normal' %>">Category</a>
        </div>
      </div>
      <div>
        <% if logged_in? %>
          <span class="text-white mr-2"><%= current_user.email %></span>
          <%= link_to "Admin", admin_root_path, class: "text-white cursor-pointer mr-2" %>
          <%= link_to "Logout", logout_path, method: :delete, class: "text-white cursor-pointer" %>
        <% else %>
          <%= link_to "Login", login_path, class: "text-white cursor-pointer" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

b2cshop/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>管理平台 - B2cshop</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= javascript_pack_tag 'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'admin', "data-turbolinks-track": 'reload' %>
</head>

<body class="bg-white">
<%= render 'layouts/admin_menu' %>
<div class="max-w-7xl mx-auto px-4">
  <% unless flash[:notice].blank? %>
    <div class="text-center py-2 px-10 bg-blue-200 text-blue-900 rounded my-4"><%= flash[:notice] %></div>
  <% end %>
  <% unless flash[:warning].blank? %>
    <div class="text-center py-2 px-10 bg-yellow-100 text-yellow-500 rounded my-4"><%= flash[:warning] %></div>
  <% end %>

  <%= yield %>
</div>

<%= debug(params) if Rails.env.development? %>
</body>
</html>

b2cshop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>B2cshop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', "data-turbolinks-track": 'reload' %>
  </head>

  <body class="bg-white">
    <%= render 'layouts/menu' %>
    <div class="max-w-7xl mx-auto px-4">
      <% unless flash[:notice].blank? %>
        <div class="text-center py-2 px-10 bg-blue-200 text-blue-900 rounded my-4"><%= flash[:notice] %></div>
      <% end %>
      <% unless flash[:warning].blank? %>
        <div class="text-center py-2 px-10 bg-yellow-100 text-yellow-500 rounded my-4"><%= flash[:warning] %></div>
      <% end %>

      <%= yield %>
    </div>

    <%= debug(params) if Rails.env.development? %>
  </body>
</html>